version: "3"

services:
  DB:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: unless-stopped
    env_file: .env.docker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '127.0.0.1:27001:27001'
    volumes:
      - db:/data/db

      
  API:
    depends_on:
      - DB
    build: .
    image: api:1.0.0
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - '127.0.0.1:1337:3000'
    environment:
      - DB_HOST=DB
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27001
  
volumes:
  db:
    driver: local
  cache:
    driver: local
